version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.36.19
    - 1.37.1
    - 1.37.20
  - dependency-name: github.com/golangci/golangci-lint
    versions:
    - 1.34.1
    - 1.36.0
